# Generated by Django 2.2.12 on 2020-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_resource',
            name='resourse_link',
            field=models.CharField(max_length=1000),
        ),
    ]
