# Generated by Django 2.2.12 on 2020-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200620_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_resource',
            name='resourse_link',
            field=models.CharField(max_length=100),
        ),
    ]
