# Generated by Django 2.2.12 on 2020-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200620_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_resource',
            name='resourse_link',
            field=models.CharField(max_length=200),
        ),
    ]
