# Generated by Django 2.2.13 on 2020-06-28 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('subprogram', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('college_name', models.CharField(default='', max_length=100)),
                ('university_name', models.CharField(default='', max_length=100)),
                ('university_skill', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('skill_set', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organisation_name', models.CharField(default='', max_length=100)),
                ('organisation_email', models.EmailField(default='', max_length=100, unique=True)),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('subjects', models.CharField(max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('job_organisation_name', models.CharField(default='', max_length=200)),
                ('job_experience', models.CharField(default='', max_length=100)),
                ('job_location', models.CharField(default='', max_length=100)),
                ('job_state', models.CharField(default='', max_length=100)),
                ('job_type', models.CharField(max_length=8)),
                ('skills', models.CharField(default='', max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='program_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subprogram_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprogram_name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='', max_length=12)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('birth_date', models.DateField()),
                ('country', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('highest_qualification', models.CharField(default='', max_length=100)),
                ('university_name', models.CharField(default='', max_length=100)),
                ('skill_set', models.CharField(max_length=100)),
                ('profileImg', models.CharField(default='photo.jpg', max_length=100)),
                ('date_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_courses', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('organisation', models.CharField(default='', max_length=100)),
                ('experience', models.CharField(default='', max_length=100)),
                ('specialisation', models.CharField(default='', max_length=100)),
                ('pastOrganisation', models.CharField(default='', max_length=100)),
                ('college_state', models.CharField(default='', max_length=100)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
    ]
