# Generated by Django 3.0.6 on 2020-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0002_program_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_details',
            name='program',
            field=models.CharField(max_length=200),
        ),
    ]
