# Generated by Django 2.2.12 on 2020-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0002_auto_20200618_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='college_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organisation_email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organisation_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='university_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='university_skill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
