# Generated by Django 3.0.6 on 2020-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0004_p_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_details',
            name='p_details',
            field=models.CharField(max_length=300),
        ),
    ]
