# Generated by Django 3.0.6 on 2020-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0005_auto_20200611_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('subprogram', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='subprogram_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprogram_name', models.CharField(max_length=300)),
                ('program', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='p_details',
        ),
    ]
