# Generated by Django 3.0.6 on 2020-06-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0006_auto_20200611_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_names',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course_names',
            name='subprogram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subprogram_details',
            name='program',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subprogram_details',
            name='subprogram_name',
            field=models.CharField(max_length=200),
        ),
    ]
